language: node_js
node_js:
    - '11'
install:
    - npm install
script:
    - hexo g
after_script:
    - cd ./public
    - git init
    - git config user.name songjianet
    - git config user.email 1778651752@qq.com
    - git add -A
    - git commit -m 'init'
    - git push -u -f "https://github.com/songjianet/blog.git" master:gh-pages
branches:
    only:
        - master
