anguage: node_js
node_js:
    - lts/*  # 稳定版 (stable) ,最新长期支持版（ - lts/* ）

# 指定缓存模块，可加快编译速度
cache:
    directories:
        - node_modules

# 在构建之前
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - npm install -g hexo-cli # 安装hexo环境

#部署环境的安装(安装一个部署插件)
install:
    - npm install
    - npm install hexo-deployer-git --save

before_script:
#

# 执行清缓存，生成网页操作
script:
    - hexo clean && hexo g

after_script:  # 未能成功
    - git config user.name "songjianet"
    - git config user.email "1778651752@qq.com"
    # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
    - sed -i "s/gh_token/${BLOG_TOKEN}/g" ./_config.yml
    - hexo deploy
